Algoritmo "ESTUDOS"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : João
// Data atual  : 24/02/2025
Var
// Seção de Declarações das variáveis 
msg: caractere

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
msg <- "Olá, Mundo!"
escreval("Mensagem ", msg)
Fimalgoritmo
